### ISSUE TITLE
Update with these links

### ISSUE THREAD

**Issue by kranurag7** [bishal7679/Missing_Link#1]
### Navbar 
- Create a new page
- Create a new page
- Replace with this link https://www.getrevue.co/profile/saiyampathak 

### Wrapper 
- Start learning - discord link 
- Workshops link (https://kubesimplify.com/workshops)
- Blog contributor - (https://kubesimplify.com/discord)
- Kubesimplify Ambassador - Google form link 

### Footer 
- give hashnode sponsor (https://kubesimplify.com/sponsor)
- remove buy me a coffee 
- kubesimplify@gmail.com is the mail.

**Comment by bishal7679** [comment]
@kranurag7 then start learning and blog contributor link will be same as discord link?

**Comment by kranurag7** [comment]
Closing this issue. Thanks for the contribution.
